Algoritmo "Identificador de Maioridade"
// Este programa irá identificar se uma pessoa atingiu a maioridade ou não
// Aluna: Maria Cristina Fabiane

Var
// Seção de Declarações das variáveis 
 id1: inteiro

Inicio
// Seção de Comandos e Saída de dados
  escreva ("Este é um identificador de maioridade, digite sua idade: ")
  leia (id1)
  
  se (id1 >=18) entao
  escreva ("Você é maior idade!")
  senao
  escreva ("Você é menor de idade!")
  Fimse

Fimalgoritmo